<?php

/**
 * Implements hook_theme().
 */
function blueoi_performance_theme($existing, $type, $theme, $path) {
  return array(
    'blueoi_performance__intro_tab' => array(
      'template' => 'blueoi-performance--intro-tab',
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function blueoi_performance_form_checklistapi_checklist_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#checklist']->id == 'blueoi_performance') {
    $form['checklistapi']['#attached']['js'][] = drupal_get_path('module', 'blueoi_performance') . '/blueoi_performance.js';
  }
}

/**
 * Implements hook_checklistapi_checklist_info().
 */
function blueoi_performance_checklistapi_checklist_info() {
  $modules_page = array('#text' => t('Enable'), '#path' => 'admin/modules');

  $definitions = array();
  $definitions['blueoi_performance'] = array(
    '#title' => t('Performance Checklist'),
    '#description' => t('Improve your websites performance by following this list of tasks.'),
    '#path' => 'admin/config/development/blueoi-performance-checklist',
    '#help' => t("<p>Check off each performance related task as you complete it. Don't forget to click the <em>Save</em> button!</p>"),

    // Introduction.
    'introduction' => array(
      '#title' => t('Introduction'),
      '#description' => theme('blueoi_performance__intro_tab'),
    ),

    // Enable modules.
    'enable_modules' => array(
      '#title' => t('Enable Performance Modules'),
      '#description' => t('<p>Helpful modules that will improve your websites performance.</p>'),
      'install_blueoi_performance' => array(
        '#title' => t('[Required] Install BlueOI Performance module.'),
        '#default_value' => module_exists('blueoi_performance'),
        'project_page' => array(
          '#text' => t('Download'),
          '#path' => 'https://github.com/andyg5000/blueoi',
        ),
        'modules_page' => $modules_page,
      ),
      'install_advagg' => array(
        '#title' => t('[Required] Install Advanced Aggregation module.'),
        '#default_value' => module_exists('advagg'),
        'project_page' => array(
          '#text' => t('Download'),
          '#path' => 'http://drupal.org/project/advagg',
        ),
        'modules_page' => $modules_page,
      ),
    ),

    // Configure modules.
    'configure_modules' => array(
      '#title' => t('Configure Performance Modules'),
      '#description' => t('<p>Configure modules to improve your websites performance.</p>'),
      'configure_performance' => array(
        '#title' => t('Configure Core Performance Settings.'),
        '#description' => t('<p><strong>Caching Settings:</strong></p><ul><li>Cache Pages for anonymous users: Yes</li><li>Cache blocks: Yes</li><li>Minimum cache lifetime: none</li><li>Expiration of cached pages: 1 day</li></ul><p><strong>Bandwidth Optimization Settings:</strong></p><ul><li>Aggregate and compress css files: Yes</li><li>Aggregate JavaScript files: Yes</li></ul>'),
        'config_page' => array(
          '#text' => t('Configure'),
          '#path' => 'admin/config/development/performance',
        ),
      ),
      'configure_advagg' => array(
        '#title' => t('Configure Advanced Aggregation module.'),
        '#description' => t('Modify the advagg configuration or use the default configuration that is deployed automtically via blueoi_performance.'),
        'config_page' => array(
          '#text' => t('Configure'),
          '#path' => 'admin/config/development/performance/advagg',
        ),
      ),
    ),

    // Cloudflare configuration.
    'cloudflare' => array(
      '#title' => t('CloudFlare Configuration'),
      '#description' => t("<p>Cloudflare speeds up and protects millions of websites, APIs, SaaS services, and other properties connected to the Internet. !link</p>", array('!link' => l(t('Signup or Login'), 'https://www.cloudflare.com/'))),
      'watch_drupal_cloudflare' => array(
        '#title' => t('Learn About Optimizing Drupal CMS with Page Rules'),
        '#description' => t('Watch Cloudflare\'s video and read documentation regarding page rule configuration for Drupal.'),
        'project_page' => array(
          '#text' => t('Learn More'),
          '#path' => 'https://www.cloudflare.com/features-page-rules/optimize-drupal/',
        ),
      ),
      'enable_ssl' => array(
        '#title' => t('Enable SSL crypto setting.'),
        '#description' => t('<p>Visit "Crypto" tab in Cloudflare and enable SSL.</p>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_htttps_redirect' => array(
        '#title' => t('Create https redirect page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> http://*example.com/*</p><p><strong>Then the settings are:</strong></p><ul><li>Always Use HTTPS</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_www_redirect' => array(
        '#title' => t('Create www redirect page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> example.com/*</p><p><strong>Then the settings are:</strong></p><ul><li>Forwarding URL: 301 - Permanent Redirect</li><li>Destination URL: https://www.example.com/$1</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_user_path' => array(
        '#title' => t('Create /user path page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> example.com/user*</p><p><strong>Then the settings are:</strong></p><ul><li>Security Level: High</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_node_path' => array(
        '#title' => t('Create /node path page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> example.com/node*/edit*</p><p><strong>Then the settings are:</strong></p><ul><li>Security Level: High</li><li>Cache Level: Bypass</li><li>Disable Apps</li><li>Disable Performance</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_admin_path' => array(
        '#title' => t('Create /admin path page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> example.com/admin*</p><p><strong>Then the settings are:</strong></p><ul><li>Browser Cache TTL: 4 hours</li><li>Security Level: High</li><li>Cache Level: Bypass</li><li>Disable Apps</li><li>Disable Performance</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_cron_path' => array(
        '#title' => t('Create /cron path page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> example.com/cron*</p><p><strong>Then the settings are:</strong></p><ul><li>Cache Level: Bypass</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
      'configure_files_path' => array(
        '#title' => t('Create /sites/default/files path page rule.'),
        '#description' => t('<p><strong>If the url matches:</strong> example.com/sites/default/files*</p><p><strong>Then the settings are:</strong></p><ul><li>Browser Cache TTL: 5 days</li><li>Cache Level: Cache Everything</li><li>Edge Cache TTL: 7 days</li></ul>'),
        'project_page' => array(
          '#text' => t('Configure'),
          '#path' => 'https://www.cloudflare.com/',
        ),
      ),
    ),

    // Test configuration.
    'test' => array(
      '#title' => t('Test Your Configuration'),
      '#description' => t("<p>Great! Now that your configuration is complete it's time to see what the results are.</p>"),
      'test_testmysite' => array(
        '#title' => t('Google: Test My Website'),
        '#description' => t('<p>Most sites lose half their visitors while loading. Test your mobile speed.</p>'),
        'project_page' => array(
          '#text' => t('Learn More'),
          '#path' => 'https://testmysite.thinkwithgoogle.com/',
        ),
      ),
      'test_insights' => array(
        '#title' => t('Google: PageSpeed Insights'),
        '#description' => t('<p>Make your web pages fast on all devices Scan your website now.</p>'),
        'project_page' => array(
          '#text' => t('Learn More'),
          '#path' => 'https://developers.google.com/speed/pagespeed/insights/',
        ),
      ),
    ),
  );

  return $definitions;
}

/**
 * Internal method to define variable default values.
 * @return array
 */
function _blueoi_performance_variable_defaults() {
  return array(
    'advagg_ajax_render_alter' => 1,
    'advagg_brotli' => false,
    'advagg_bundler_active' => 1,
    'advagg_bundler_grouping_logic' => '0',
    'advagg_bundler_max_css' => '1',
    'advagg_bundler_max_js' => '4',
    'advagg_cache_level' => '3',
    'advagg_combine_css_media' => 1,
    'advagg_convert_absolute_to_protocol_relative_path' => 1,
    'advagg_convert_absolute_to_relative_path' => 1,
    'advagg_core_groups' => false,
    'advagg_cron_frequency' => '86400',
    'advagg_cron_timestamp' => 1501215748,
    'advagg_css_compressor' => '2',
    'advagg_css_compress_inline' => '0',
    'advagg_css_compress_inline_if_not_cacheable' => 0,
    'advagg_css_fix_type' => 1,
    'advagg_css_remove_empty_files' => 0,
    'advagg_disable_on_admin' => 0,
    'advagg_enabled' => 1,
    'advagg_force_https_path' => 0,
    'advagg_gzip' => 1,
    'advagg_htaccess_symlinksifownermatch' => 0,
    'advagg_ie_css_selector_limiter' => 1,
    'advagg_ie_css_selector_limiter_value' => '4095',
    'advagg_include_base_url' => 0,
    'advagg_js_compressor' => '5',
    'advagg_js_compress_add_license' => '0',
    'advagg_js_compress_inline' => '0',
    'advagg_js_compress_inline_if_not_cacheable' => 0,
    'advagg_js_compress_packer' => 0,
    'advagg_js_fix_type' => 1,
    'advagg_js_remove_empty_files' => 0,
    'advagg_mod_css_adjust_sort_browsers' => 0,
    'advagg_mod_css_adjust_sort_external' => 0,
    'advagg_mod_css_adjust_sort_inline' => 0,
    'advagg_mod_css_defer' => '0',
    'advagg_mod_css_defer_admin' => 0,
    'advagg_mod_css_defer_js_code' => '0',
    'advagg_mod_css_defer_pages' => '',
    'advagg_mod_css_defer_skip_first_file' => '0',
    'advagg_mod_css_defer_visibility' => '0',
    'advagg_mod_css_head_extract' => 0,
    'advagg_mod_css_preprocess' => 0,
    'advagg_mod_defer_inline_js_skip_list' => '',
    'advagg_mod_ga_inline_to_file' => 0,
    'advagg_mod_inline_css_pages' => '',
    'advagg_mod_inline_css_visibility' => '1',
    'advagg_mod_inline_js_pages' => '',
    'advagg_mod_inline_js_visibility' => '1',
    'advagg_mod_inline_pages' => '',
    'advagg_mod_inline_visibility' => '1',
    'advagg_mod_js_adjust_sort_browsers' => 1,
    'advagg_mod_js_adjust_sort_external' => 1,
    'advagg_mod_js_adjust_sort_inline' => 1,
    'advagg_mod_js_async' => 0,
    'advagg_mod_js_async_in_header' => 1,
    'advagg_mod_js_async_shim' => 0,
    'advagg_mod_js_defer' => '0',
    'advagg_mod_js_defer_inline_alter' => 0,
    'advagg_mod_js_footer' => '0',
    'advagg_mod_js_footer_inline_alter' => 0,
    'advagg_mod_js_head_extract' => 1,
    'advagg_mod_js_inline_resource_hints' => false,
    'advagg_mod_js_no_ajaxpagestate' => 0,
    'advagg_mod_js_preprocess' => 0,
    'advagg_mod_js_remove_unused' => 1,
    'advagg_mod_prefetch' => 0,
    'advagg_mod_unified_multisite_dir' => '',
    'advagg_mod_wrap_inline_js_skip_list' => '',
    'advagg_mod_wrap_inline_js_xpath' => 0,
    'advagg_remove_missing_files_from_db_time' => '1209600',
    'advagg_remove_old_unused_aggregates_time' => '3888000',
    'advagg_resource_hints_dns_prefetch' => 0,
    'advagg_resource_hints_location' => 1,
    'advagg_resource_hints_preconnect' => 0,
    'advagg_resource_hints_preload' => 0,
    'advagg_resource_hints_preload_settings' => array (
      'style' =>
        array (
          '#weight' => '-10',
          'enabled' => 1,
          'external' => 1,
          'local' => 1,
          'push' => 0,
        ),
      'font' =>
        array (
          '#weight' => '-9',
          'enabled' => 1,
          'external' => 1,
          'local' => 1,
          'push' => 0,
        ),
      'script' =>
        array (
          '#weight' => '-8',
          'enabled' => 1,
          'external' => 1,
          'local' => 1,
          'push' => 0,
        ),
      'svg' =>
        array (
          '#weight' => '-7',
          'enabled' => 1,
          'external' => 1,
          'local' => 1,
          'push' => 0,
        ),
      'image' =>
        array (
          '#weight' => '-6',
          'enabled' => 1,
          'external' => 1,
          'local' => 1,
          'push' => 0,
        ),
      'all_others' =>
        array (
          '#weight' => '-5',
          'enabled' => 1,
          'external' => 1,
          'local' => 1,
          'push' => 0,
        ),
    ),
    'advagg_resource_hints_use_immutable' => 1,
    'advagg_root_dir_prefix' => 'public://',
    'advagg_skip_file_create_url_inside_css' => 1,
    'advagg_use_httprl' => false,
  );
}

/**
 * Sets variables.
 *
 * @param array $variables
 *   An array of variable_name (key) => variable_value (value) pairs to be set.
 */
function blueoi_performance_set_variables($variables = array()) {
  // Loop over variables and set values.
  foreach ($variables as $variable => $value) {
    variable_set($variable, $value);
  }
}
