<?php

/**
 * @file
 * Module file for blueoi_mail.module.
 */

/**
 * Implements hook_menu().
 */
function blueoi_mail_menu() {
  $items = array();

  // Provide a page callback that allows easy theming of
  // email templates.
  $items['blueoi/themed-email'] = array(
    'title' => 'Themed Email',
    'page callback' => 'blueoi_mail_themed_mail_view',
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Page callback for blueoi/themed-email to render mail content.
 */
function blueoi_mail_themed_mail_view() {
  drupal_page_is_cacheable(FALSE);
  $content = module_invoke_all('blueoi_mail_themed_mail_view');
  $output = theme('mimemail_message', array('body' => render($content)));
  print $output;
  drupal_exit();
}

/**
 * @param $markup
 *   The HTML markup to be used in a message template.
 * @param $message
 *   A message entity.
 *
 * @return string
 *   Simulated markup that a message would return.
 */
function blueoi_mail_simulate_message($markup, $message) {
  $context = array('message' => $message);
  $token_options = message_get_property_values($message, 'data', 'token options');
  $output = token_replace($markup, $context, $token_options);
  return $output;
}
